requires 'Kossy', '0.40';
requires 'DBIx::Sunny';
requires 'DBD::mysql';
requires 'LWP::UserAgent';
requires 'List::MoreUtils';
requires 'List::UtilsBy';
requires 'JSON::XS';
requires 'URI';
requires 'String::Random';
requires 'Digest::SHA1';
requires 'Path::Tiny';
requires 'Plack::App::Proxy';
requires 'Plack::Session';
requires 'Starlet';
requires 'Furl';

requires 'Server::Starter';
requires "Gazelle";
requires "Plack::Middleware::Session::Simple";
requires "Cache::Memcached::Fast";
requires "Sereal";
requires 'List::UtilsBy';
